name: 'Compile and install VTest'
description: 'Compiles and installs VTest into the PATH.'
author: 'Tim Düsterhus'
inputs:
  branch:
    required: true
    description: 'VTest branch to install.'
  GITHUB_TOKEN:
    required: true
    description: 'The value of secrets.GITHUB_TOKEN.'
outputs:
  commit:
    description: 'The exact VTest commit that was installed.'
runs:
  using: 'node16'
  main: 'dist/index.js'
